### ISSUE TITLE
Let's Encrypt!

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/anthonymastrean.github.io#36]
General availability: Week of November 16, 2015

https://letsencrypt.org/2015/08/07/updated-lets-encrypt-launch-schedule.html

**Comment by AnthonyMastrean** [comment]
General availability: Week of November 16, 2015

https://letsencrypt.org/2015/08/07/updated-lets-encrypt-launch-schedule.html

**Comment by AnthonyMastrean** [comment]
Or https://dnsimple.com/ssl-certificate

**Comment by AnthonyMastrean** [comment]
Waiting on github: https://github.com/isaacs/github/issues/156

**Comment by tbodt** [comment]
Jut use netlify.com. They have an extremely simple setup process, and can directly use your existing github pages (enter `jekyll build` as the build command.)

**Comment by AnthonyMastrean** [comment]
https://blog.dnsimple.com/2016/11/lets-encrypt/
